// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MinecraftVariant = { "type": "Vanilla" } | { "type": "Forge" } | { "type": "Fabric" } | { "type": "Paper" } | { "type": "Spigot" } | { "type": "Neoforge" } | { "type": "Other", name: string, };